apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  VIRTUAL_HOST: http://localhost:8080
  VIRTUAL_PORT: "3000"
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-service:5432/db_depocheck
  SPRING_DATASOURCE_USERNAME: depocheck
  JWT_SECRET: thisIsMysecregtfrdesww233eggtffeeddgkjjhhtdhttebd54ndhdhfhhhshs8877465sbbdd
  FRONTEND_URL: http://localhost:8081
  SPRING_JPA_HIBERNATE_DDL_AUTO: update